version: '3.5'

networks:
  whmcs:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

# nginx
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
      - ${WHMCS_PATH}:/var/www/html
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./.data/logs-nginx/:/var/log/nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
    depends_on:
      - php-fpm
    networks:
      - whmcs

# PHP-FPM
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: ${PHP_VERSION}.Dockerfile
    volumes:
      - ${WHMCS_PATH}:/var/www/html
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=xwhmcs
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - whmcs

# MySQL
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - whmcs

# maildev - to test emails
  maildev:
    build: ./maildev
    ports:
      - "${MAILDEV_HTTP_PORT}:80"
      - "${MAILDEV_SMTP_PORT}:25"
    networks:
      - whmcs
